INSERT INTO product_description
VALUES  (1, 'Indulge in the Ultimate Comfort with Our Exquisite Beds<br/><br/>Discover a sanctuary of relaxation with our meticulously crafted beds. Each bed is a masterpiece of design and functionality, offering a perfect blend of style and comfort. Our curated collection features a variety of styles, from modern and sleek to timeless classics, ensuring there''s a perfect match for every bedroom.<br/><br/>Immerse yourself in the plush luxury of our carefully selected materials, providing a sumptuous retreat for a restful night''s sleep. Whether you prefer the clean lines of contemporary design or the elegance of traditional craftsmanship, our beds are crafted to exceed your expectations.<br/><br/>Unwind in style as our beds seamlessly blend aesthetics and practicality. Choose from a range of sizes and finishes to complement your bedroom decor. Elevate your sleep experience with the finest in bed craftsmanship—because a good night''s sleep begins with the perfect bed.',
         './image/hammer_1.png', 4),
        (2, 'Embrace Relaxation with Our Comfort Chairs<br/><br/>Experience the epitome of comfort with our thoughtfully designed Comfort Chairs. Each chair is a harmonious blend of style and ergonomic perfection, offering a cozy retreat for moments of relaxation. Our curated collection showcases a diverse range of designs, from modern recliners to timeless classics, ensuring you find the ideal seat for your space.<br/><br/>Immerse yourself in the luxurious upholstery and ergonomic features that define our Comfort Chairs. Whether you seek the sleek lines of contemporary design or the enduring appeal of traditional craftsmanship, our chairs are crafted to elevate your comfort.<br/><br/>Discover unparalleled support and style as our chairs seamlessly merge aesthetics with functionality. Choose from an array of sizes, materials, and finishes to complement your living space. Elevate your leisure time with the finest in chair craftsmanship—because true comfort begins with the perfect seat.',
         './image/shovel_1.png', 5),
        (3, 'Effortless Simplicity, Timeless Comfort with Our Basic Chair<br/><br/>Introducing our Basic Chair, where simplicity meets comfort in a timeless design. This chair is a perfect embodiment of minimalist elegance, offering a versatile seating solution for any space. Our carefully curated collection features a range of styles, from sleek and modern to understated classics, ensuring that there''s a Basic Chair to suit every taste.<br/><br/>Experience the essential comfort of our Basic Chair, designed for both functionality and aesthetics. Crafted with quality materials and a focus on clean lines, this chair provides a straightforward yet stylish addition to any room.<br/><br/>With a commitment to simplicity and comfort, our Basic Chair seamlessly integrates into various settings. Choose from different sizes and finishes to effortlessly enhance your living space. Enjoy the pure essence of seating with our Basic Chair—because sometimes, less is truly more.',
         './image/hoe_1.png', 3),
        (4, 'Optimal Comfort, Productivity, and Style with Our Computer Chair<br/><br/>Introducing our Computer Chair, the perfect fusion of ergonomic design and contemporary style. This chair is meticulously crafted to enhance your workspace, providing the ideal balance of comfort and functionality. Our thoughtfully curated collection features a variety of designs, from sleek and modern to professional classics, ensuring that there''s a Computer Chair to complement any office or study.<br/><br/>Immerse yourself in the superior comfort and functionality of our Computer Chair, designed to support you during long work hours. With adjustable features and quality materials, this chair is a stylish addition to any modern workspace.',
         './image/rake_1.png', 4);
